.POSIX:

CFLAGS = -ffreestanding -Wall\
         -Wextra -fno-exceptions\
         -std=gnu17 -fno-pic\
         -fstack-protector-all

LDFLAGS = -nostdlib -lgcc\
          -ffreestanding -fno-pie

CC = /usr/local/i386elfgcc-11.1.0/bin/i386-elf-gcc
CP = /usr/bin/cp
DATE = /usr/bin/date
NASM = /usr/bin/nasm
ECHO = /usr/bin/echo
MKDIR = /usr/bin/mkdir
ISOMAKER = /usr/bin/grub-mkrescue
