.POSIX:

CFLAGS = -g -ffreestanding -Wall -Wextra -fno-exceptions -m32 -std=gnu99 -Os
LDFLAGS = -nostdlib -lgcc -ffreestanding -Os

# Change this if your cross-compiler is somewhere else
CC = /usr/local/i386elfgcc-10.2.0/bin/i386-elf-gcc
CP = /usr/bin/cp
DATE = /usr/bin/date
NASM = /usr/bin/nasm
ECHO = /usr/bin/echo
MKDIR = /usr/bin/mkdir
ISOMAKER = /usr/bin/grub-mkrescue
